[build]
  builder = "NIXPACKS"
  buildCommand = "pip install -r requirements.txt"

[deploy]
  startCommand = "cd watch_finder_v2/backend/api && python app.py"
  healthcheckPath = "/api/health"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"

[env]
  ENVIRONMENT = "production"
  PYTHONPATH = "/app/watch_finder_v2/backend"
  RAILWAY_URL = "https://web-production-36c3.up.railway.app" 