[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Handle Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects to Railway backend
[[redirects]]
  from = "/api/*"
  to = "https://web-production-a75cb.up.railway.app/api/:splat"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/_next/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400" 