[build]
  builder = "NIXPACKS"
  buildCommand = "pip install -r requirements.txt"

[deploy]
  startCommand = "api/production_linucb_app.py"
  healthcheckPath = "/api/health"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"

[env]
  ENVIRONMENT = "production"
  PYTHONPATH = "/app"
  RAILWAY_URL = "https://web-production-36c3.up.railway.app" 