[build]
  builder = "NIXPACKS"
  buildCommand = "pip install -r requirements.txt && mkdir -p images && cp -r ../../production_scrape_20250601_175426/images/* images/"

[deploy]
  startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 120 --preload api.simple_sgd_app:app"
  healthcheckPath = "/api/health"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"

[env]
  ENVIRONMENT = "production"
  PYTHONPATH = "/app"
  RAILWAY_URL = "https://web-production-36c3.up.railway.app"